server:
  port: 8700
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  mvc:
    static-path-pattern: /image/**
  resources:
    static-locations: file:D://image/
  datasource:
    url: jdbc:mysql://49.235.193.231:3306/videoplayer?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: test01
    password: aaaaaa
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
logging:
  file:
    path: D:\VueProjects\shop\log
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
